GoodreadsDataAnalysisProject/Controllers/FavoriteBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoodreadsDataAnalysis.Data;
using GoodreadsDataAnalysis.Models;
using Microsoft.AspNetCore.Authorization;

namespace GoodreadsDataAnalysis.Controllers
{
    public class FavoriteBooksController : Controller
    {
        private readonly ApplicationDBContext _context;

        public FavoriteBooksController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
              //list of all book results
              return _context.FavoriteBooks != null ? 
                          View(await _context.FavoriteBooks.ToListAsync()) :
                          Problem("Entity set 'ApplicationDBContext.Book'  is null.");
        }
        // GET: Books/ShowSeachForm
        public IActionResult ShowSearchForm()
        {
            return View();
        }

        // POST: Books/ShowSeachResults
        // parameter names need to match the input name from the specified view
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            //list of filtered book results
            return _context.FavoriteBooks != null ?
                          View("Index", await _context.FavoriteBooks.Where(
                                b => b.Title.Contains(SearchPhrase) || 
                                b.Genre.Contains(SearchPhrase) || 
                                b.Author.Contains(SearchPhrase)).ToListAsync()) :
                          Problem("Entity set 'ApplicationDBContext.FavoriteBook'  is null.");
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.FavoriteBooks == null)
            {
                return NotFound();
            }

            var book = await _context.FavoriteBooks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Title,Author,Genre")] FavoriteBook book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.FavoriteBooks == null)
            {
                return NotFound();
            }

            var book = await _context.FavoriteBooks.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Author,Genre")] FavoriteBook book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.FavoriteBooks == null)
            {
                return NotFound();
            }

            var book = await _context.FavoriteBooks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.FavoriteBooks == null)
            {
                return Problem("Entity set 'ApplicationDBContext.FavoriteBook'  is null.");
            }
            var book = await _context.FavoriteBooks.FindAsync(id);
            if (book != null)
            {
                _context.FavoriteBooks.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.FavoriteBooks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GoodreadsDataAnalysisProject/Controllers/GoodreadsAnalysisController.cs
using GoodreadsDataAnalysis.Data;
using GoodreadsDataAnalysis.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GoodreadsBookAnalysis.Controllers
{
    public class GoodreadsAnalysisController : Controller
    {

        private readonly BooksDBContext _context;
        public GoodreadsAnalysisController(BooksDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<GoodreadsBook> topBooks5Star = _context.GoodreadsBooks
            .OrderByDescending(book => book.Ratings5)
            .Take(5)
            .Select(book => new GoodreadsBook
            {
                OriginalTitle = book.OriginalTitle,
                Authors = book.Authors,
                //AverageRating = book.AverageRating,
                //CountOf5StarRatings = book.Ratings5
            }).AsNoTracking();

            return View("Index", topBooks5Star);
        }
    }
}

GoodreadsDataAnalysisProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Goodreads Data Analysis</title>
    <link rel="stylesheet" href="~/css/VaporCustomTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/GoodreadsDataAnalysis.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Goodreads Data Analysis</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="GoodreadsAnalysis" asp-action="Index">Goodreads Data Analysis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="FavoriteBooks" asp-action="Index">Favorite Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="FavoriteBooks" asp-action="ShowSearchForm">Book Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    @* <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search Favorite Books">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form> *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="border-top text-muted">
        <div class="container">
            &copy; 2023 - Goodreads Data Analysis Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>